# Generated by Django 5.2.4 on 2025-08-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="school_name",
            field=models.CharField(
                blank=True,
                help_text="School or institution name",
                max_length=100,
                null=True,
            ),
        ),
    ]
