# Generated by Django 5.2.4 on 2025-08-03 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_question_anticipators_alter_answer_upvoters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="upvoters",
            field=models.ManyToManyField(
                blank=True, related_name="upvoted_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="anticipators",
            field=models.ManyToManyField(
                blank=True,
                related_name="anticipated_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
